create table question_list
(
    qid         int auto_increment comment '题库唯一id',
    type        int          not null comment '试题类型 1单选，2多选，3其他',
    question    varchar(300) not null comment '问题',
    options     json         not null comment '选项：json类型，因为可能有多个选项或者其他格式的
[]',
    answer      json         not null comment '答案',
    questionImg blob         null comment '图片',
    constraint question_list_qid_uindex
        unique (qid)
)
    comment '题库';

alter table question_list
    add primary key (qid);

INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (1, 1, '一家公司刚刚成为了一家跨国公司。员工在不同的时区远程工作，他们需要随时从任何地方访问公司服务。什么服务或技术可以支持这个需求？', '[{"optionName": "A", "optionValue": "云服务"}, {"optionName": "B", "optionValue": "ASI"}, {"optionName": "C", "optionValue": "虚拟化"}, {"optionName": "D", "optionValue": "计算中心"}]', '["B"]', null);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (7, 1, '下面哪一项陈述正确描述了云计算的概念？', '[{"optionName": "A", "optionValue": "从硬件分离操作系统"}, {"optionName": "B", "optionValue": "从数据平面分离控制平面"}, {"optionName": "C", "optionValue": "从硬件分离应用"}, {"optionName": "D", "optionValue": "从控制平面分离管理平面"}]', '["C"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (8, 1, '一家小型公司正在考虑将其数据中心的许多功能转移到云中。此计划的三个优势是什么?(选择三项。)', '[{"optionName": "A", "optionValue": "公司不需要担忧如何通过内部数据中心设备来满足不断增长的数据存储和处理需求。"}, {"optionName": "B", "optionValue": "公司不需要担忧如何通过内部数据中心设备来满足不断增长的数据存储和处理需求。 单租户数据中心可以轻松扩展，以满足不断增长的数据存储需求。 云服务支持公司拥有并管理自己的服务器和存储设备。 公司只需为它所使用的那部分处理和存储容量付款。 公司可以根据需求增加处理和存储容量，然后在其不需要时减少容量。 云服务采用固定资费，不论公司使用多少处理和存储容量都是如此。"}, {"optionName": "C", "optionValue": "云服务支持公司拥有并管理自己的服务器和存储设备。"}, {"optionName": "D", "optionValue": "公司只需为它所使用的那部分处理和存储容量付款。"}, {"optionName": "E", "optionValue": "公司可以根据需求增加处理和存储容量，然后在其不需要时减少容量。"}, {"optionName": "F", "optionValue": "云服务采用固定资费，不论公司使用多少处理和存储容量都是如此。"}]', '["A", "D", "E"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (9, 1, '下列哪种类型的黑客会被激发去抗议政治和社会问题？', '[{"optionName": "A", "optionValue": "漏洞经纪人"}, {"optionName": "B", "optionValue": "网络犯罪分子"}, {"optionName": "C", "optionValue": "脚本小子"}, {"optionName": "D", "optionValue": "激进黑客"}]', '["D"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (10, 1, '特洛伊木马恶意软件的最佳描述是什么？', '[{"optionName": "A", "optionValue": "它是只能通过 Internet 进行散布的恶意软件。"}, {"optionName": "B", "optionValue": "它是最容易检测到的恶意软件形式。"}, {"optionName": "C", "optionValue": "它是导致烦人但不严重的计算机问题的软件。"}, {"optionName": "D", "optionValue": "它看起来是有用的软件，但却隐藏着恶意代码。"}]', '["D"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (11, 1, '什么是 ping 扫描？', '[{"optionName": "A", "optionValue": "一种查询和响应协议，用于标识域相关信息，包括分配给该域的地址。"}, {"optionName": "B", "optionValue": "一种软件应用，可捕获通过局域网发送的所有网络数据包。"}, {"optionName": "C", "optionValue": "一种网络扫描技术，用于指示一系列 IP 地址中的动态主机。"}, {"optionName": "D", "optionValue": "一种扫描技术，检查主机上的一系列 TCP 或 UDP 端口号以检测侦听服务。"}]', '["C"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (12, 1, '以下情景使用了什么攻击：威胁发起者将自己置于源和目标之间，从而能够悄悄地监测、捕获和控制源和目的之间的通信。', '[{"optionName": "A", "optionValue": "DoS 攻击"}, {"optionName": "B", "optionValue": "中间人攻击"}, {"optionName": "C", "optionValue": "ICMP 攻击"}, {"optionName": "D", "optionValue": "SYN 泛洪攻击"}]', '["B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (13, 1, '在哪种类型的攻击中，虚假信息用于将用户重定向至恶意互联网站点？', '[{"optionName": "A", "optionValue": "DNS 缓存毒化"}, {"optionName": "B", "optionValue": "域生成"}, {"optionName": "C", "optionValue": "DNS 放大和反射"}, {"optionName": "D", "optionValue": "ARP 缓存毒化"}]', '["A"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (14, 1, '通过实施 MD5 或 SHA 散列生成算法确保了哪种安全通信要求？', '[{"optionName": "A", "optionValue": "认证"}, {"optionName": "B", "optionValue": "保密性"}, {"optionName": "C", "optionValue": "不可否认性"}, {"optionName": "D", "optionValue": "完整性"}]', '["D"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (15, 1, '哪个通配符掩码可以用来匹配网络172.16.0.0到172.19.0.0？', '[{"optionName": "A", "optionValue": "0.252.255.255"}, {"optionName": "B", "optionValue": "0.3.255.255"}, {"optionName": "C", "optionValue": "0.0.3.255"}, {"optionName": "D", "optionValue": "0.0.255.255"}]', '["B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (16, 2, '网络管理员在 IPv4 扩展 ACL 上可以使用哪两个数据包过滤器？（请选择两项。）', '[{"optionName": "A", "optionValue": "目的 UDP 端口号"}, {"optionName": "B", "optionValue": "计算机类型"}, {"optionName": "C", "optionValue": "目的 MAC 地址"}, {"optionName": "D", "optionValue": "ICMP 消息类型"}, {"optionName": "E", "optionValue": "源 TCP hello 地址"}]', '["A", "D"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (17, 1, '什么类型的 ACL 提供更大的灵活性和对网络访问的更好控制？', '[{"optionName": "A", "optionValue": "灵活"}, {"optionName": "B", "optionValue": "已命名的标准"}, {"optionName": "C", "optionValue": "扩展"}, {"optionName": "D", "optionValue": "已编号的标准"}]', '["C"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (19, 1, '从指定 ACL 中删除单个 ACE 的最快方法是什么？', '[{"optionName": "A", "optionValue": "使用 no 关键字和待删除 ACE 序号。"}, {"optionName": "B", "optionValue": "使用 no access-list 命令删除整个 ACL，然后重新创建无 ACE 的 ACL。"}, {"optionName": "C", "optionValue": "在 ACL 复制到文本编辑器中，删除 ACE，然后将 ACL 再复制回路由器中。"}, {"optionName": "D", "optionValue": "创建编号不同的新 ACL，并将该新的 ACL 应用至路由器接口。"}]', '["A"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (20, 1, '请参见图示。网络管理员如图所示配置了ACL 9。172.31.1.0/24网络中的用户无法通过路由器CiscoVille转发流量。导致流量转发失败最可能的原因是什么？', '[{"optionName": "A", "optionValue": "未指定 established 关键字。"}, {"optionName": "B", "optionValue": "permit语句中指定了错误的通配符掩码。"}, {"optionName": "C", "optionValue": "未使用 eq 关键字来标识流量的端口号。"}, {"optionName": "D", "optionValue": "ACE 的顺序不正确。"}]', '["D"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (21, 2, '网络管理员需要配置一个标准ACL，使得只有IP地址为192.168.15.23的管理员工作站可以访问主路由器的虚拟终端。下列哪两条命令可以完成这个任务？（选择两项。）', '[{"optionName": "A", "optionValue": "Router1(config)# access-list 10 permit 192.168.15.23 255.255.255.0"}, {"optionName": "B", "optionValue": "Router1(config)# access-list 10 permit 192.168.15.23 255.255.255.255"}, {"optionName": "C", "optionValue": "Router1(config)# access-list 10 permit host 192.168.15.23"}, {"optionName": "D", "optionValue": "Router1(config)# access-list 10 permit 192.168.15.23 0.0.0.0"}, {"optionName": "E", "optionValue": "Router1(config)# access-list 10 permit 192.168.15.23 0.0.0.255"}]', '["C", "D"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (22, 1, '请参见图示。在标准 ACL 中，哪一命令将用于仅允许连接至 R2 G0/0 接口的网络上设备访问连接至 R1 的网络？', '[{"optionName": "A", "optionValue": "access-list 1 permit 192.168.10.0 0.0.0.255"}, {"optionName": "B", "optionValue": "access-list 1 permit 192.168.10.96 0.0.0.31"}, {"optionName": "C", "optionValue": "access-list 1 permit 192.168.10.128 0.0.0.63"}, {"optionName": "D", "optionValue": "access-list 1 permit 192.168.10.0 0.0.0.63"}]', '["B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (23, 1, '请参见图示。在 R1 上配置 ACL，拒绝流量从子网 172.16.4.0/24 进入子网 172.16.3.0/24。应允许所有其他流量进入子网 172.16.3.0/24。然后，将该标准 ACL 应用至接口 Fa0/0 出站。从该配置可以得出哪一结论？', '[{"optionName": "A", "optionValue": "请参见图示。在 R1 上配置 ACL，拒绝流量从子网 172.16.4.0/24 进入子网 172.16.3.0/24。应允许所有其他流量进入子网 172.16.3.0/24。然后，将该标准 ACL 应用至接口 Fa0/0 出站。从该配置可以得出哪一结论？"}, {"optionName": "B", "optionValue": "在该情况下必须使用扩展 ACL。"}, {"optionName": "C", "optionValue": "为符合要求，应将 ACL 应用中 R1 FastEthernet 0/0 接口入站。"}, {"optionName": "D", "optionValue": "应阻止所有流量，而不仅仅是来自 172.16.4.0/24 子网的流量。"}, {"optionName": "E", "optionValue": "仅阻止来自子网 172.16.4.0/24 的流量，允许所有其他流量。"}]', '["D"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (24, 1, '请参见图示。网络管理员需将 ACE 添加至拒绝来自子网 172.23.16.0/20 之 IP 流量的 TRAFFIC-CONTROL ACL。哪一 ACE 将满足此要求？', '[{"optionName": "A", "optionValue": "5 deny 172.23.16.0 0.0.15.255"}, {"optionName": "B", "optionValue": "5 deny 172.23.16.0 0.0.255.255"}, {"optionName": "C", "optionValue": "30 deny 172.23.16.0 0.0.15.255"}, {"optionName": "D", "optionValue": "15 deny 172.23.16.0 0.0.15.255"}]', '["A"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (25, 1, '将 Router1(config-ext-nacl)# permit tcp 172.16.4.0 0.0.0.255 any eq www 命令应用到 f0/0 接口的入站方向上会有什么效果？', '[{"optionName": "A", "optionValue": "会允许来自 172.16.4.0/24 的所有流量发往任意端口。"}, {"optionName": "B", "optionValue": "会允许所有 TCP 流量，但拒绝其它所有流量。"}, {"optionName": "C", "optionValue": "路由器会拒绝该命令，因为该命令不完整。"}, {"optionName": "D", "optionValue": "会允许从 172.16.4.0/24 始发的流量发往所有 TCP 端口 80 目的地。"}]', '["D"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (26, 1, '请参见图示。从该输出可以得到什么结论？', '[{"optionName": "A", "optionValue": "路由器尚无任何来自 10.35.80.22 的以 10.23.77.101 为目的地的 Telnet 数据包。"}, {"optionName": "B", "optionValue": "由于第 10 行没有匹配，ACL 不工作。"}, {"optionName": "C", "optionValue": "ACL 缺少 deny ip any any ACE。"}, {"optionName": "D", "optionValue": "ACL 只监控来自三个特定主机的以 10.23.77.101 为目的地的流量。"}]', '["A"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (28, 2, '请参见图示。网络管理员想要仅允许主机 192.168.1.1 /24 能够访问服务器 192.168.2.1 /24。哪三个命令将使用最佳 ACL 放置做法实现此目的？（选择三项。）', '[{"optionName": "A", "optionValue": "R2(config)# access-list 101 permit ip host 192.168.1.1 host 192.168.2.1"}, {"optionName": "B", "optionValue": "R2(config-if)# ip access-group 101 in"}, {"optionName": "C", "optionValue": "R2(config)# access-list 101 permit ip 192.168.1.0 255.255.255.0 192.168.2.0 255.255.255.0"}, {"optionName": "D", "optionValue": "R2(config)# interface fastethernet 0/1"}, {"optionName": "E", "optionValue": "R2(config)# interface fastethernet 0/0"}, {"optionName": "F", "optionValue": "R2(config-if)# ip access-group 101 out"}, {"optionName": "G", "optionValue": "R2(config)# access-list 101 permit ip any any"}]', '["A", "B", "E"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (29, 1, '在全局配置模式中输入 ip access-list standard aaa 命令后，CLI 提示符会变成为什么？', '[{"optionName": "A", "optionValue": "Router(config)#"}, {"optionName": "B", "optionValue": "Router(config-router)#"}, {"optionName": "C", "optionValue": "Router(config-if)#"}, {"optionName": "D", "optionValue": "Router(config-line)#"}, {"optionName": "E", "optionValue": "Router(config-std-nacl)#"}]', '["E"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (30, 1, '下列哪个ACE允许源自任意网络的流量去往IP地址为192.168.1.1的Web服务器？', '[{"optionName": "A", "optionValue": "access-list 101 permit tcp host 192.168.1.1 any eq 80"}, {"optionName": "B", "optionValue": "access-list 101 permit tcp any eq 80 host 192.168.1.1"}, {"optionName": "C", "optionValue": "access-list 101 permit tcp host 192.168.1.1 eq 80 any"}, {"optionName": "D", "optionValue": "access-list 101 permit tcp any host 192.168.1.1 eq 80"}]', '["D"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (31, 1, '请参见图示。新的网络策略要求使用ACL拒绝所有实习生通过FTP和Telnet访问公司的文件服务器。文件服务器的地址为 172.16.1.15，所有实习生都会获得 172.18.200.0/24 网络的地址。应用了 ACL 后，企业网中没有人可以访问任何服务器。问题出在哪里？', '[{"optionName": "A", "optionValue": "对于入站ACL来说，必须先对数据包进行路由，才会使用ACL进行处理。"}, {"optionName": "B", "optionValue": "ACL会通过隐式拒绝语句拒绝所有去往服务器的流量。"}, {"optionName": "C", "optionValue": "在命名ACL中要求使用端口号。"}, {"optionName": "D", "optionValue": "在接口的错误方向上应用了ACL。"}]', '["B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (32, 2, '请考虑以下访问列表。   access-list 100 permit ip host 192.168.10.1 any  access-list 100 deny icmp 192.168.10.0 0.0.0.255 any echo  access-list 100 permit ip any any   如果该访问列表被置于已分配 IP 地址 192.168.10.254 路由器千兆以太网端口上，则会采取两项操作？（选择两项。）', '[{"optionName": "A", "optionValue": "192.168.10.0/24 网络上的设备不能回应任何 ping 请求。"}, {"optionName": "B", "optionValue": "分配此访问列表后，允许从 192.168.10.0 上的任何设备到路由器的 Telnet 或 SSH 会话。"}, {"optionName": "C", "optionValue": "192.168.10.0/24 网络上的设备可以成功 ping 通 192.168.11.0 网络上的设备。"}, {"optionName": "D", "optionValue": "仅允许已分配 IP 地址 192.168.10.1 的网络设备访问路由器。"}, {"optionName": "E", "optionValue": "只允许从路由器到任何其他网络设备的第 3 层连接。"}]', '["B", "C"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (33, 1, '在哪种针对 TCP 的攻击中，网络犯罪分子试图用半开 TCP 连接淹没目标主机？', '[{"optionName": "A", "optionValue": "SYN 泛洪攻击"}, {"optionName": "B", "optionValue": "会话劫持攻击"}, {"optionName": "C", "optionValue": "重置攻击"}, {"optionName": "D", "optionValue": "端口扫描攻击"}]', '["A"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (34, 1, '网络犯罪分子提供无效网关创建中间人攻击时，哪一协议受到攻击？', '[{"optionName": "A", "optionValue": "DNS"}, {"optionName": "B", "optionValue": "HTTP 或 HTTPS"}, {"optionName": "C", "optionValue": "DHCP"}, {"optionName": "D", "optionValue": "ICMP"}]', '["C"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (35, 1, '请参见图示。管理员在 R1 上配置了标准 ACL，并将其应用在串行 S0/0/0 接口的出站方向上。如果从S0/0/0接口发出的流量与配置的 ACL 语句不匹配，会发生什么情况？', '[{"optionName": "A", "optionValue": "具体的行为取决于目的IP地址。"}, {"optionName": "B", "optionValue": "流量会被丢弃。"}, {"optionName": "C", "optionValue": "检查源IP地址，如果没有找到匹配项，流量会从S0/0/1接口路由出去。"}, {"optionName": "D", "optionValue": "具体的行为取决于目的IP地址和端口号。"}]', '["B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (36, 2, '请参见图示。两台路由器的千兆接口都已配置了与其相连的 VLAN 编号相匹配的子接口编号。VLAN 10 上的 PC 应该可以打印内容到 VLAN 12 上的 P1 打印机。VLAN 20 上的 PC 应该打印内容到 VLAN 22 上的打印机。您应该使用什么接口、在什么方向放置一个标准的 ACL，使其允许从数据 VLAN 10 打印到 P1，但阻止 VLAN 20 上的 PC 使用 P1 打印机？（请选择两项。）', '[{"optionName": "A", "optionValue": "出站"}, {"optionName": "B", "optionValue": "R1 Gi0/1.12"}, {"optionName": "C", "optionValue": "R2 Gi0/1.20"}, {"optionName": "D", "optionValue": "入站"}, {"optionName": "E", "optionValue": "R2 S0/0/1"}, {"optionName": "F", "optionValue": "R1 S0/0/0"}]', '["A", "B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (37, 1, '下列哪项描述了标准 IPv4 ACL 的特点？', '[{"optionName": "A", "optionValue": "它们仅根据源 IP 地址过滤流量。"}, {"optionName": "B", "optionValue": "它们是在接口配置模式下配置的。"}, {"optionName": "C", "optionValue": "创建它们时可以使用数字，但不可以使用名称。"}, {"optionName": "D", "optionValue": "可以根据源 IP 地址和源端口对过滤流量进行配置。"}]', '["A"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (38, 1, '在vty线路上配置ACL的最佳实践是什么？', '[{"optionName": "A", "optionValue": "删除vty线路上的密码，因为已经使用ACL只放行受信任的用户进行访问。"}, {"optionName": "B", "optionValue": "在所有vty线路上应用相同的限制。"}, {"optionName": "C", "optionValue": "在入站方向上应用命令 ip access-group 。"}, {"optionName": "D", "optionValue": "仅使用扩展访问列表。"}]', '["B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (39, 2, '请参见图示。管理员首先配置了一个扩展 ACL，详见 show access-lists 命令的输出所示。然后，管理员使用下列命令来编辑编辑这个访问列表。 Router(config)# ip access-list extended 101  Router(config-ext-nacl)# no 20  Router(config-ext-nacl)# 5 permit tcp any any eq 22  Router(config-ext-nacl)# 20 deny udp any any  从新的配置中可以得出以下哪两个结论？（选择两项。） ', '[{"optionName": "A", "optionValue": "放行SSH数据包。"}, {"optionName": "B", "optionValue": "放行TFTP数据包。"}, {"optionName": "C", "optionValue": "放行 Ping 数据包。"}, {"optionName": "D", "optionValue": "拒绝所有TCP和UDP数据包。"}, {"optionName": "E", "optionValue": "放行 Telnet 数据包。"}]', '["A", "C"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (40, 1, '哪组访问控制条目将允许 192.168.10.0/24 网络上的所有用户访问位于 172.17.80.1 的 Web 服务器，但是不允许他们使用 Telnet？', '[{"optionName": "A", "optionValue": "access-list 103 permit tcp 192.168.10.0 0.0.0.255 any eq 80  access-list 103 deny tcp 192.168.10.0 0.0.0.255 any eq 23 "}, {"optionName": "B", "optionValue": "access-list 103 permit tcp 192.168.10.0 0.0.0.255 host 172.17.80.1 eq 80  access-list 103 deny tcp 192.168.10.0 0.0.0.255 any eq 23"}, {"optionName": "C", "optionValue": "access-list 103 permit 192.168.10.0 0.0.0.255 host 172.17.80.1  access-list 103 deny tcp 192.168.10.0 0.0.0.255 any eq telnet​​ "}, {"optionName": "D", "optionValue": "access-list 103 deny tcp host 192.168.10.0 any eq 23  access-list 103 permit tcp host 192.168.10.1 eq 80 "}]', '["B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (41, 1, '以下哪个术语描述了这类人：他们会通过发布文章和视频、泄漏敏感信息以及执行网络攻击，来公开抗议组织机构或政府？', '[{"optionName": "A", "optionValue": "白帽黑客"}, {"optionName": "B", "optionValue": "激进黑客"}, {"optionName": "C", "optionValue": "灰帽黑客"}, {"optionName": "D", "optionValue": "国家资助的黑客"}]', '["B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (42, 1, '请参见图示。网络管理员的IP地址是192.168.11.10，他需要对R1发起管理访问。在这种情况下，最佳的ACL类型是什么，应用位置是哪里？', '[{"optionName": "A", "optionValue": "在R2连接互联网的WAN接口的入站方向上应用标准ACL"}, {"optionName": "B", "optionValue": "在R1的vty线路入站方向上应用标准ACL"}, {"optionName": "C", "optionValue": "在R2 S0/0/0接口的出站方向上应用标准ACL"}, {"optionName": "D", "optionValue": "在R2 S0/0/0接口的入站方向上应用扩展ACL"}]', '["B"]', 0x);
INSERT INTO examhepler.question_list (qid, type, question, options, answer, questionImg) VALUES (43, 1, '一位技术人员要通过实施ACL来保护路由器。他在什么时候会使用 no ip access-list 101 配置选项或命令？', '[{"optionName": "A", "optionValue": "需要保护路由器的管理访问时"}, {"optionName": "B", "optionValue": "在所有路由器接口上应用ACL时"}, {"optionName": "C", "optionValue": "需要从路由器上删除所有ACL时"}, {"optionName": "D", "optionValue": "需要删除配置中的ACL时"}]', '["D"]', 0x);